---
title: "Recherches"
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(fig.path = "images/",
               cache.path = "cache/",
               cache = FALSE,
               echo = FALSE, #set to false to hide code
               message = FALSE,
               warning = FALSE,
               out.width = "100%",
               dpi = 200,
               fig.align = "center")
```

<script>
function hide_buttons(abstract) {
    var x = document.getElementById(abstract);
    if (x.style.display === "none") {
        x.style.display = "block";
    } else {
        x.style.display = "none";
    }
}
</script>

## Projets

### Analyse et comparaison des conditions de travail dans le secteur de la restauration

Ce projet réalisé dans le cadre de la [Journée nationale Evrest 2024](https://evrest.istnf.fr/page-59-0-0.html#menu), s'attache à étudier les conditions de travail du secteur de la restauration et d'analyser les éventuels effets que peuvent avoir ces conditions de travail sur la santé des salarié·es de ce secteur. Par ailleurs, il s'agissait également de s'intéresser aux différences au sein même du secteur entre les salarié·es travaillant en salle et celles et ceux travaillant en cuisine. 


[Poster - Congrès National Médecine Santé-Travail 2024](/Users/maireem/Desktop/Evrest/Restauration/Poster-Restauration_Maire.pdf)

### Projet Manaos

Bientôt

### Quelle place de la ségrégation professionnelle dans les inégalités de conditions de travail ?

Ce travail a été réalisé dans le cadre du mémoire de master de [Sociologie du Travail du Cnam](https://formation.cnam.fr/rechercher-par-discipline/master-grh-et-sociologie-du-travail-1085619.kjsp) sous la direction de [Yaël Brinbaum](https://lise-cnrs.cnam.fr/le-laboratoire/les-membres-du-lise/yael-brinbaum-lise-ceet--918897.kjsp). 
Ce travail s'attache à interroger la place des effets de structure, de la ségrégation professionnelle, dans les inégalités séxuées de conditions de travail. Une présentation aura lieu lors du congrès de l'AfS 2025. 


## Publications

Un jour. Peut-être. Ou jamais.
