---
title: "Recherche"
---

```{r setup, include=FALSE}
library(knitr)
opts_chunk$set(fig.path = "images/",
               cache.path = "cache/",
               cache = FALSE,
               echo = FALSE, #set to false to hide code
               message = FALSE,
               warning = FALSE,
               out.width = "100%",
               dpi = 200,
               fig.align = "center")
```

<script>
function hide_buttons(abstract) {
    var x = document.getElementById(abstract);
    if (x.style.display === "none") {
        x.style.display = "block";
    } else {
        x.style.display = "none";
    }
}
</script>

## Projets

### Evrest (ÉVolution des RElations Santé-Travail)

L'observatoire [***Evrest***](https://evrest.istnf.fr/page-0-0-0.html) est un observatoire de veille et de recherche en santé au travail. Cet observatoire est piloté au niveau national par des chercheurs et chercheuses ainsi que des médecins et infirmier·ères du travail. 

### Les conditions de travail des tuteurs et tutrices 

Ce travail a été réalisé avec [***Serge Volkoff***](https://ceet.cnam.fr/le-ceet/chercheur-euse-s/serge-volkoff-988483.kjsp) et [***Céline Mardon***](https://ceet.cnam.fr/le-ceet/chercheur-euse-s/celine-mardon-crtd-ceet--988365.kjsp) et s'attache à document les conditions de travail des tuteurs et tutrices en entreprise à partir des données de l'observatoire Evrest. 
Ce travail a été présenté lors du [séminaire annuel du Creapt 2024](https://ceet.cnam.fr/le-ceet/evenements-actualites-du-ceet/la-construction-des-savoirs-professionnels-au-fil-des-parcours-ressources-et-obstacles--1465243.kjsp?RH=1528808070600) (actes à paraître) et fait l'objet d'un travail de valorisation avec Samira Mahlaoui et Jean-Paul Cadet du [Céreq](https://www.cereq.fr/).


### Les conditions de travail dans le secteur de la restauration

Ce travail s'attache à étudier les conditions de travail dans le secteur de la restauration en 2018-2019, en les comparant aux autres secteurs d'activité présents dans la base Evrest. Il s'agit également de regarder au sein du secteur les différences entre les métiers de la salle et ceux de la cuisine. Ce travail a été présenté lors de la [journée nationale Evrest 2024](https://evrest.istnf.fr/page-59-0-0.html#menu) (capation de la présentation disponible) et a également fait l'objet d'un [poster](Documents/Poster-Restauration_Maire.pdf) lors du Congrès National de Médecine Santé-Travail 2024.

### Quelle place de la ségrégation professionnelle dans les inégalités sexuées de conditions de travail ? 

Ce travail a été réalisé dans le cadre d'un mémoire de master de Sociologie du Travail du Cnam sous la direction de [Yaël Brinbaum](https://lise-cnrs.cnam.fr/le-laboratoire/les-membres-du-lise/yael-brinbaum-lise-ceet--918897.kjsp). Ce travail vise à étudier les inégalités sexuées de conditions de travail et d'analyser la place de la ségrégation professionnelle sexuée dans ces inégalités. Ce travail fera l'objet d'une présentation lors du congrès de l'AfS en juillet 2025. 


## Publications

Un jour. Peut-être. Ou sinon jamais.
